openapi: 3.0.3
info:
  title: Super Job API
  description: Документация Super Job API
  version: 1.0.0
servers:
  - url: 'https://xn--h1aafpog.xn--90ahbflhjgobv0ae.xn--p1ai/superjob/api'
    description: Beget release server
paths:
  /worker/{token}:
    get:
      summary: Метод получения соискателя по токену
      tags:
        - Соискатель
      operationId: getWorkerByToken
      parameters:
        - name: token
          in: path
          required: false
          description: Токен соискателя
          schema:
            type: string
          example: marvel
        - in: header
          name: appkey
          schema:
            type: integer
            example: 0000
          required: true
      responses:
        '200':
          description: Успешное получение соискателя по токену
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
    post:
      summary: Метод добавления соискателя
      tags:
        - Соискатель
      operationId: addWorker
      parameters:
        - in: header
          name: appkey
          schema:
            type: integer
            example: 0000
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Worker"
      responses:
        '200':
          description: Успешное добавление соискателя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseAddWorker"


components:
  schemas:
    Response:
      type: object
      properties:
        status:
          type: boolean
          example: true
        content:
          $ref: "#/components/schemas/Worker"
        message:
          type: string
          example: Success
    ResponseAddWorker:
      type: object
      properties:
        status:
          type: boolean
          example: true
        content:
          example: null
        message:
          type: string
          example: Worker has been created
    Worker:
      type: object
      properties:
        token:
          type: string
          example: marvel
          description: Токен соискателя
        name:
          type: string
          example: Evgeny
          description: Имя соискателя
        age:
          type: string
          example: 34
          description: Возраст
        town:
          type: string
          example: Yakutsk
          description: Город, населенный пункт проживания
